#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 18 15:38:30 2020

@author: hsjhinkwan
"""

inf1 = ["I am a human being",1]
inf2 = ["I am good",2]
inf3 = ["Good graders study well",3]
inf4 = ["Every human does not study well",4]

a = inf1[0]
p = a.split()
print(p)

